services:
  - type: web
    name: âœ¦â˜ ï¸ğ•°ğ–›ğ–ğ–‘ ğ•¹~ğ•¸~ğ•·â™«âƒâœ™.-pair-site
    env: docker
    plan: free
    branch: main
    repo: https://github.com/NM-Test01/âœ¦â˜ ï¸ğ•°ğ–›ğ–ğ–‘ ğ•¹~ğ•¸~ğ•·â™«âƒâœ™.
    dockerfilePath: ./Dockerfile
    autoDeploy: true
